// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCoreTest.Dal.EFCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyCoreTest.Migrations
{
    [DbContext(typeof(ConversationContext))]
    [Migration("20190714204204_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domains.Conversation.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("CreatedBy");

                    b.Property<string>("Message");

                    b.Property<int>("SourceId");

                    b.HasKey("ItemId");

                    b.HasIndex("SourceId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Domains.Conversation.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("CreatedBy");

                    b.Property<string>("Name");

                    b.Property<bool>("Rmv");

                    b.HasKey("SourceId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Domains.Conversation.Item", b =>
                {
                    b.HasOne("Domains.Conversation.Source", "Source")
                        .WithMany("Items")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
